-- MySQL Script generated by MySQL Workbench
-- qui 23 abr 2026 14:24:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `user_nome` VARCHAR(255) NULL,
  `user_email` VARCHAR(255) NULL,
  `user_senha` VARCHAR(255) NULL,
  `user_telefone` CHAR(14) NULL,
  `user_fotos` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresario` (
  `idempresario` INT NOT NULL,
  `empre_tipo` VARCHAR(255) NOT NULL,
  `empre_dias_trab` VARCHAR(255) NOT NULL,
  `empre_cidade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idempresario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `prod_nome` VARCHAR(255) NULL,
  `prod_marca` VARCHAR(255) NULL,
  `prod_fotos` VARCHAR(45) NULL,
  `empresario_idempresario` INT NOT NULL,
  PRIMARY KEY (`idprodutos`, `empresario_idempresario`),
  INDEX `fk_produtos_empresario1_idx` (`empresario_idempresario` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_empresario1`
    FOREIGN KEY (`empresario_idempresario`)
    REFERENCES `mydb`.`empresario` (`idempresario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agenda` (
  `idagenda` INT NOT NULL AUTO_INCREMENT,
  `agend_horario` DATETIME NOT NULL,
  `agend_dia` VARCHAR(255) NULL,
  `agend_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idagenda`, `agend_idusuarios`),
  INDEX `fk_agenda_usuarios1_idx` (`agend_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_usuarios1`
    FOREIGN KEY (`agend_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicos` (
  `idservicos` INT NOT NULL AUTO_INCREMENT,
  `serv_nome` VARCHAR(255) NOT NULL,
  `serv_valor` DECIMAL NOT NULL,
  `serv_descricao` VARCHAR(255) NOT NULL,
  `serv_tempo` TIME NOT NULL,
  `serv_fotos` VARCHAR(45) NOT NULL,
  `agenda_idagenda` INT NOT NULL,
  `empresario_idempresario` INT NOT NULL,
  PRIMARY KEY (`idservicos`, `agenda_idagenda`, `empresario_idempresario`),
  INDEX `fk_servicos_agenda1_idx` (`agenda_idagenda` ASC) VISIBLE,
  INDEX `fk_servicos_empresario1_idx` (`empresario_idempresario` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_agenda1`
    FOREIGN KEY (`agenda_idagenda`)
    REFERENCES `mydb`.`agenda` (`idagenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_empresario1`
    FOREIGN KEY (`empresario_idempresario`)
    REFERENCES `mydb`.`empresario` (`idempresario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `idcomentarios` INT NOT NULL,
  `coment_texto` VARCHAR(255) NULL,
  `coment_idusuarios` INT NOT NULL,
  `comentarios_estrela` INT(1) NULL,
  PRIMARY KEY (`idcomentarios`, `coment_idusuarios`),
  INDEX `fk_comentarios_usuarios1_idx` (`coment_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`coment_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emp_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emp_user` (
  `empresario_idempresario` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`empresario_idempresario`, `usuarios_idusuarios`),
  INDEX `fk_empresario_has_usuarios_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_empresario_has_usuarios_empresario1_idx` (`empresario_idempresario` ASC) VISIBLE,
  CONSTRAINT `fk_empresario_has_usuarios_empresario1`
    FOREIGN KEY (`empresario_idempresario`)
    REFERENCES `mydb`.`empresario` (`idempresario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresario_has_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horarios` (
  `idhorarios` INT NOT NULL,
  `horarios_dia_semana` VARCHAR(45) NULL,
  `horarios_hora_inicio` VARCHAR(45) NULL,
  `horarios_hora_fim` VARCHAR(45) NULL,
  `empresario_idempresario` INT NOT NULL,
  `agenda_idagenda` INT NOT NULL,
  PRIMARY KEY (`idhorarios`, `empresario_idempresario`, `agenda_idagenda`),
  INDEX `fk_horarios_empresario1_idx` (`empresario_idempresario` ASC) VISIBLE,
  INDEX `fk_horarios_agenda1_idx` (`agenda_idagenda` ASC) VISIBLE,
  CONSTRAINT `fk_horarios_empresario1`
    FOREIGN KEY (`empresario_idempresario`)
    REFERENCES `mydb`.`empresario` (`idempresario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarios_agenda1`
    FOREIGN KEY (`agenda_idagenda`)
    REFERENCES `mydb`.`agenda` (`idagenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
